/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SportNFT } from "./SportNFT";
export type { SportNFTMarketplace } from "./SportNFTMarketplace";
